server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024
spring:
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/db_loja_virtual
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
