server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024
spring:
  application:
    name: loja-virtual
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/db_loja_virtual
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#    show-sql: true
#    format-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

secretKey: 1b2d7a2079285f016ee03c922440bdfaa6cdc31ab0e0a9f98c018b6528ae78d4

logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug
security:
  ignored: /**